### PR TITLE
Use biothings with_total to efficiently batch query

### PR DESCRIPTION
**Pull request by tokebe**
*Implements https://github.com/biothings/BioThings_Explorer_TRAPI/issues/483*

For biothings pending APIs, the new `with_total` will be used to support intelligent paging to get additional results.

*requires biothings/api-respone-transform.js#33*

### CODE REVIEW

**Comment by colleenXu** [comment]
@tokebe

Question: is this implemented only on pending BioThings APIs (not the core BioThings)?

Note: this requires all pending BioThings APIs to use "biothings.ncats.io" urls for their server urls (in the SmartAPI yamls). I checked and only 1 API was using "pending.biothings.io" so I changed it https://github.com/NCATS-Tangerine/translator-api-registry/commit/9caa70b6223795d7e3a837c7966737fc5a2e9284#diff-da82f38db560ed04902de14a1caaf9df2b3e9df4395726b5ab89b11afefcb065
This will need to be kept in mind in the future too...

**Comment by colleenXu** [comment]
Testing (still editing, in-progress)

<details>
<summary>send to team-specific endpoint Service Provider</summary>

Query TP53 -> Disease (should get a lot of records)

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["NCBIGene:7157"],
		            "categories":["biolink:Gene"]
                },
                "n1": {
                    "categories": ["biolink:Disease"]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    }
}
```
</details>

without the PRs, logs show several semmeddb queries hit the 1000-max 
```
  bte:call-apis:query call-apis: Successful POST https://biothings.ncats.io/semmeddb (2 IDs): Gene > associated_with > Disease (obtained 1000 records, took 1s) +344ms
  bte:call-apis:query call-apis: Successful POST https://biothings.ncats.io/semmeddb (2 IDs): Gene > part_of > Disease (obtained 1000 records, took 2s) +340ms
  bte:call-apis:query call-apis: Successful POST https://biothings.ncats.io/semmeddb (2 IDs): Gene > affects > Disease (obtained 1000 records, took 774ms) +327ms
```

with the PRs, scrolling queries are seen

<details>
<summary>semmeddb Gene > associated_with > Disease operation's logs</summary>

Initial query: notice that `with_total` parameter is used, logs say pagination/scrolling is needed
```
   bte:call-apis:query {
  bte:call-apis:query   url: 'https://biothings.ncats.io/semmeddb/query',
  bte:call-apis:query   params: {
  bte:call-apis:query     with_total: true,
  bte:call-apis:query     fields: 'object.umls,pmid,subject.umls,subject.name,predicate,object.name',
  bte:call-apis:query     size: 1000
  bte:call-apis:query   },
  bte:call-apis:query   data: {
  bte:call-apis:query     q: [ [Array], [Array] ],
  bte:call-apis:query     scopes: [
  bte:call-apis:query       'subject.umls',
  bte:call-apis:query       'predicate',
  bte:call-apis:query       'object.semantic_type_abbreviation',
  bte:call-apis:query       'subject.novelty',
  bte:call-apis:query       'object.novelty'
  bte:call-apis:query     ]
  bte:call-apis:query   },
  bte:call-apis:query   method: 'post',
  bte:call-apis:query   timeout: 50000,
  bte:call-apis:query   headers: { 'User-Agent': 'BTE/dev Node/v17.8.0 darwin' }
  bte:call-apis:query } +4ms

  bte:call-apis:query This query needs to be paginated +332ms
  bte:call-apis:query call-apis: Successful POST https://biothings.ncats.io/semmeddb (2 IDs): Gene > associated_with > Disease (obtained 1000 records, took 2s) +0ms
  bte:call-apis:query query success, transforming hits->records... +4ms
```

Subsequent queries: notice that `from` is used (for scrolling) and `with_total` is still used. Logs say pagination/scrolling is still needed.
```
  bte:call-apis:query {
  bte:call-apis:query   url: 'https://biothings.ncats.io/semmeddb/query',
  bte:call-apis:query   params: {
  bte:call-apis:query     with_total: true,
  bte:call-apis:query     fields: 'object.umls,pmid,subject.umls,subject.name,predicate,object.name',
  bte:call-apis:query     size: 1000,
  bte:call-apis:query     from: 1000
  bte:call-apis:query   },

  bte:call-apis:query This query needs to be paginated +304ms
  bte:call-apis:query call-apis: Successful POST https://biothings.ncats.io/semmeddb (2 IDs): Gene > associated_with > Disease (obtained 1000 records, took 776ms) +0ms


  bte:call-apis:query {
  bte:call-apis:query   url: 'https://biothings.ncats.io/semmeddb/query',
  bte:call-apis:query   params: {
  bte:call-apis:query     with_total: true,
  bte:call-apis:query     fields: 'object.umls,pmid,subject.umls,subject.name,predicate,object.name',
  bte:call-apis:query     size: 1000,
  bte:call-apis:query     from: 2000

  bte:call-apis:query This query needs to be paginated +294ms
  bte:call-apis:query call-apis: Successful POST https://biothings.ncats.io/semmeddb (2 IDs): Gene > associated_with > Disease (obtained 1000 records, took 532ms) +0ms
```

The last sub-query was `from: 9000`, retrieved 1000 records, and didn't have a lot mentioning "needs pagination"
```
  bte:api-response-transform:index api name BioThings SEMMEDDB API +826ms
  bte:api-response-transform:index api tags: disease,phenotype,gene,chemical,association,query,translator,biothings,ngd +0ms
  bte:call-apis:query call-apis: Successful POST https://biothings.ncats.io/semmeddb (2 IDs): Gene > associated_with > Disease (obtained 1000 records, took 535ms) +302ms
```

</details>

This makes me wonder. @tokebe do you think BTE or the BioThings API reached a max of 10,000 hits? Maybe you can dig into what the `with_total` value was for this specific operation (one of the https://biothings.ncats.io/semmeddb (2 IDs): Gene > associated_with > Disease)...

**Comment by colleenXu** [comment]
@tokebe Maybe the logs could be clearer around pagination? Maybe replacing `call-apis: This query needs to be paginated` with something like this: `Paginating still needed for https://biothings.ncats.io/semmeddb (2 IDs): Gene > associated_with > Disease. Scrolling from 2000 - 3000`

**Comment by colleenXu** [comment]
TDLR:
* This looks good
* I had some questions that involve looking into [BioThings](https://github.com/biothings/call-apis.js/pull/59#issuecomment-1251637762) APIs, [sub-queries](https://github.com/biothings/call-apis.js/pull/59#issuecomment-1251674929)
* I had a comment on the [logs](https://github.com/biothings/call-apis.js/pull/59#issuecomment-1251693308)

**Comment by tokebe** [comment]
@colleenXu Let's see what I can address here:
- This PR, as implemented, requires `biothings.ncats.io` -- I could change this to be more general `biothings` or just add `pending.biothings.io`, if that change would make more sense. I was unaware there were differing standards here. Core biothings (mygene, etc.) are not subject to this PR's new behavior.
- BTE's querying automatically stops at 10,000 so as to not hit the biothings limit.
- I'm not 100% sure on the cases where it's retrieving <1000 per window. I'll have to investigate. It's possible a large number of hits are, for some reason or another, not valid/miss criteria for becoming records, since the log is about records rather than hits, but that's pure speculation. I'll update after I've looked into it.
- I can make a change to make the log a bit more straightforward.

**Comment by tokebe** [comment]
I've confirmed, cases where we're getting <1000 records in a window of 1000, we *are* getting 1000 hits, they're just converting to fewer records. I'm updating the log to display both hits and records for clarity.

**Comment by tokebe** [comment]
@colleenXu given the upcoming move to `biothings.transltr.io`, it may make sense for me to simply change the implementation to check for `biothings` in the URL. Do you foresee any issues with that/should I implement it differently?

**Comment by colleenXu** [comment]
Hmm, in response to [this](https://github.com/biothings/call-apis.js/pull/59#issuecomment-1252561356),  https://github.com/biothings/call-apis.js/pull/59#issuecomment-1252561356, I think it would help to match on "biothings" (would work whether someone uses `pending.biothings.io`, `biothings.ncats.io`, or the switch-over to `biothings.transltr.io`)...But we could try checking with @newgene or searching the smartapi_specs.json / SmartAPI registry to see if "biothings" shows up in any urls that aren't actually for pending BioThings APIs?

---

And it [sounds](https://github.com/biothings/call-apis.js/pull/59#issuecomment-1252546003) like "[records](url)" is a more useful thing to say than "hits" for some logs? The vocab work is coming to mind :P 

---

I think I'm forgetting...so the with_total POST parameter wasn't implemented on the core biothings APIs yet? @newgene 

---

Also, [on the 10,000 limit thing](https://github.com/biothings/call-apis.js/pull/59#issuecomment-1252486645)...it makes me wonder if we can sort certain POST responses (to get the "best" stuff) or set more query criteria (to get fewer matching records)... 
But this may involve looking into each API that gets into this situation (maybe we can raise a WARNING log when this happens and/or somehow record when this happens)? 

I noticed this on a semmeddb query....and there are already other issues related to semmeddb...
* https://github.com/biothings/BioThings_Explorer_TRAPI/issues/501
* https://github.com/biothings/pending.api/issues/63#issue-1190213033 with Yao's issues https://github.com/biothings/semmeddb/issues

**Comment by colleenXu** [comment]
@tokebe @newgene found one potential issue: OpenPredict is tagged with "biothings" and maybe has x-bte annotation. However, BTE currently doesn't use this resource and I haven't reviewed their x-bte annotation (they're also a TRAPI service...)

**Comment by colleenXu** [comment]
@tokebe @newgene Also there are no more biothings APIs that are using `pending.biothings.io` as their server url...I [changed](https://github.com/Hadlock-Lab/clinical_risk_kp/commit/c56789f11a4461f49f9cc5e54f919952f8094269) multiomics ehr risk's yaml and refreshed the [registration](http://smart-api.info/registry?q=d86a24f6027ffe778f84ba10a7a1861a).

**Comment by tokebe** [comment]
Worth noting that this PR only works for APIs tagged biothings and using templated mode. As long as their x-bte isn't using templates we should be fine.

Also, isn't their tagging as 'biothings' an improper tag in this case? Should they remove it?

**Comment by colleenXu** [comment]
hmmm....not all biothings-API yamls are using templating >.<. It sounds like that's something to put into my to-do list? 

And yeah, I think it's improper but I'm not sure...

**Comment by tokebe** [comment]
@colleenXu Yes, that would be something to work on down the line. It was agreed in initial discussion (on Zoom, so no record to link to, sorry) that this feature should only support templated queries.

@newgene Would you characterize OpenPredict tagging as `biothings` an improper use of the tag?

**Comment by tokebe** [comment]
Last [demotest run](https://api.bte.ncats.io/demotests/compare?old=results-2022-09-22&new=results-2022-09-26-m0) including this and ngd expansion looked good, I think we can prepare to merge and deploy and just ping OpenPredict about removing their biothings tag.

**Pull request merged**
